version: '3.5'

services:

  service_container:
    container_name: Service_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env 

    ports:
      - ${REST_PORT_OUT}:${REST_PORT_INP}
    depends_on:
      postgres:
        condition: service_healthy

            
      
  postgres:
    container_name: Pg_Database
    image: postgres
    env_file:
      - .env 
    environment:
      POSTGRES_DB: ${PG_DATABASE}

      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS} 
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 3


    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
